// <auto-generated />
using System;
using GymOrganization.Infrastructure.ApplicationDbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymOrganization.Infrastructure.Migrations
{
    [DbContext(typeof(GymOrganizationDbContext))]
    [Migration("20231204141202_Add catalog entity")]
    partial class Addcatalogentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("GymOrganization.Infrastructure.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f32ee00-8974-4215-8fd8-07e0befaf890"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("b7612d57-bb44-4913-8c7f-8a6aba4fe3d5"),
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = new Guid("4a1999ca-3693-4f60-afbe-22a77fef2f09"),
                            Name = "Coach",
                            NormalizedName = "COACH"
                        });
                });

            modelBuilder.Entity("GymOrganization.Infrastructure.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e563aa88-86b1-4c69-a0f8-496b53c9ac26"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8a9bb2dc-fd86-4d36-b819-a6423b3016df",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jsmith@example.com",
                            EmailConfirmed = false,
                            FirstName = "John",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "JSMITH@EXAMPLE.COM",
                            NormalizedUserName = "JSMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPFl1WjFq8adcY44o2Qiyw+VnnXRM9ygG11bruyAHl4uzoR6daZaJbFVQvGXg+MQvw==",
                            PhoneNumber = "+1-555-123-4567",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5899b002-6ebc-411c-ac42-f1f214717792",
                            TwoFactorEnabled = false,
                            UserName = "jsmith@example.com"
                        },
                        new
                        {
                            Id = new Guid("d4a4a0ca-d7cb-4e8f-8c58-34535c9eab5b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "990a5f9d-6ca6-4895-99d1-b8907970bd21",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jdoe@example.com",
                            EmailConfirmed = false,
                            FirstName = "Jane",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JDOE@EXAMPLE.COM",
                            NormalizedUserName = "JDOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECLyTUL+Yk/Tqct2aaAflttkGsWA0Mv75JeSf2svuk0Gf/UX8mkTrvKovCFw+vJZew==",
                            PhoneNumber = "+1-555-987-6543",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f7cc212d-1fab-40f1-b7ed-c2dbc3d9a7f3",
                            TwoFactorEnabled = false,
                            UserName = "jdoe@example.com"
                        },
                        new
                        {
                            Id = new Guid("87d8fde7-99da-4a9c-9cfc-64bfc84d7196"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "12083a79-ee49-429b-8375-7539ccb31215",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bjohnson@example.com",
                            EmailConfirmed = false,
                            FirstName = "Bob",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "BJOHNSON@EXAMPLE.COM",
                            NormalizedUserName = "BJOHNSON@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELzqlJbrjGn9v6bfe21XNrHDbjDz3+RR8yKHq8WtjU9REI5wNdbxvnq0HlPc54PdEw==",
                            PhoneNumber = "+1-555-555-1212",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "34395ab6-9a94-4c6f-9638-6e199a9165a4",
                            TwoFactorEnabled = false,
                            UserName = "bjohnson@example.com"
                        },
                        new
                        {
                            Id = new Guid("1e9deac9-7e9d-46d6-997a-32efdf6d5f6c"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4b9c1ccb-66e5-46b0-961d-4640c63c5692",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "asmith@example.com",
                            EmailConfirmed = false,
                            FirstName = "Alice",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "ASMITH@EXAMPLE.COM",
                            NormalizedUserName = "ASMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENO7f0y8xwrIkfaD18Myd9I3i5fW+UlIlN2By5AFuK3m1lbDMYNUSO30QhXMxETNxA==",
                            PhoneNumber = "+1-555-999-1212",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "85689bdf-bb3a-49ca-823f-8245048c4766",
                            TwoFactorEnabled = false,
                            UserName = "asmith@example.com"
                        },
                        new
                        {
                            Id = new Guid("af690bfe-f82e-4856-b8dc-1075a5f5c6b9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "66f2ebf1-90df-4ee6-89db-fb59d5b2d819",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tlee@example.com",
                            EmailConfirmed = false,
                            FirstName = "Tom",
                            LastName = "Lee",
                            LockoutEnabled = false,
                            NormalizedEmail = "TLEE@EXAMPLE.COM",
                            NormalizedUserName = "TLEE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE3l2q6o2/bM99lp8+xUrAKyvehWjB+u7qvZo7nqlTOw83X145g2G4DNMhSvAjRI0g==",
                            PhoneNumber = "+1-555-444-1212",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9dc3566b-e761-4c47-b17f-04cb84205d52",
                            TwoFactorEnabled = false,
                            UserName = "tlee@example.com"
                        });
                });

            modelBuilder.Entity("GymOrganization.Infrastructure.Entities.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CatalogItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c20d7354-5b9a-4c41-8bf0-6f0f50aecc49"),
                            Description = "Доступ до тренажерного залу та занять на один місяць.",
                            Price = 1500.0,
                            ShortName = "Щомісячний Абонемент"
                        },
                        new
                        {
                            Id = new Guid("583842e8-ee0a-4f2f-bc52-68b68602aef0"),
                            Description = "Особистий тренувальний сеанс з сертифікованим тренером.",
                            Price = 350.0,
                            ShortName = "Тренування з Тренером"
                        },
                        new
                        {
                            Id = new Guid("8ef93f07-0d22-4f0d-8a5b-8b0d34d5fde8"),
                            Description = "Одне заняття на наших оживляючих йога-класах.",
                            Price = 80.0,
                            ShortName = "Йога - Одноразове Відвідування"
                        },
                        new
                        {
                            Id = new Guid("d8719de1-7386-4848-aafe-c11439a61c12"),
                            Description = "Доступ до тренажерного залу на один день.",
                            Price = 150.0,
                            ShortName = "Одноразове Відвідування"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d4a4a0ca-d7cb-4e8f-8c58-34535c9eab5b"),
                            RoleId = new Guid("2f32ee00-8974-4215-8fd8-07e0befaf890")
                        },
                        new
                        {
                            UserId = new Guid("e563aa88-86b1-4c69-a0f8-496b53c9ac26"),
                            RoleId = new Guid("4a1999ca-3693-4f60-afbe-22a77fef2f09")
                        },
                        new
                        {
                            UserId = new Guid("87d8fde7-99da-4a9c-9cfc-64bfc84d7196"),
                            RoleId = new Guid("4a1999ca-3693-4f60-afbe-22a77fef2f09")
                        },
                        new
                        {
                            UserId = new Guid("1e9deac9-7e9d-46d6-997a-32efdf6d5f6c"),
                            RoleId = new Guid("b7612d57-bb44-4913-8c7f-8a6aba4fe3d5")
                        },
                        new
                        {
                            UserId = new Guid("af690bfe-f82e-4856-b8dc-1075a5f5c6b9"),
                            RoleId = new Guid("b7612d57-bb44-4913-8c7f-8a6aba4fe3d5")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("GymOrganization.Infrastructure.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GymOrganization.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GymOrganization.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("GymOrganization.Infrastructure.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymOrganization.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GymOrganization.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
